# Section 1: Visualising sedimentary data 
## Subsection 1: In a ternary diagram 
```{r}
#Creating a matrix with three chosen sediments types 
ternary_mat <- locations[,c('clay','silt','sand')]

#Generating the ternary diagram
ternary(ternary_mat, labels=c("Clay", "Silt", "Sand"),type='p', col='grey')
```

## Subsection 2: Through a biplot
```{r}
#Principle Component Analysis
components <- clr(ternary_mat) #making the data easier to read
pc <- prcomp(components) #principal component analysis of the data

#Generating biplot
biplot(pc, col=c("grey", "black"), xlim=c(-0.2,0.25)) #change limits slightly to allow clay to be viewed on the biplot
```

# Section 2: Interpolating Erosion Rates
```{r}
#Parameters for semivariogram 
X <- locations$E #east west axis
Y <- locations$N #north south axis
Z <- locations$erosion #value for erosion

#Finding the right semivariogram
svm_exp <- semivariogram(x=X,y=Y,z=Z,model='exponential', main='Exponential Semivariogram') #Fitting exponential model
svm_gau <- semivariogram(x=X,y=Y,z=Z,model='gaussian', main='Gaussian Semivariogram') #Fitting Gaussian model
svm_sph <- semivariogram(x=X,y=Y,z=Z,model='spherical', main='Spherical Semivariogram') #Fitting spherical model

#Gaussian distribution seems to subjectively fit the line, therefore, svm_gau is used for interpolation
xi <- seq(from=min(X),to=max(X),length.out=50)
yi <- seq(from=min(Y),to=max(Y),length.out=50)
zi <- kriging(x=X,y=Y,z=Z,svm=svm_gau,xi=xi,yi=yi,grid=TRUE)
colourplot(x=xi,y=yi,z=zi,key.title=title('Erosion rates (mm/yr)'), xlab='Eastings', ylab='Northings', main ='Interpolation of erosion rates' )

#Uncertainties with interpolation 
zi_error <- kriging(x=X,y=Y,z=Z,svm=svm_gau,xi=xi,yi=yi,grid=TRUE,err=TRUE)
colourplot(x=xi,y=yi,z=sqrt(zi_error),key.title=title('s[Erosion rate]/Erosion Rate'), xlab='Eastings', ylab='Northings', main = 'Interpolation Uncertainty')
```

# Section 3: Evaluating the model 
## Subsection 1: Dividing samples into two groups
```{r}
biplot(pc, col=c("grey", "black"), xlim=c(-0.2,0.25))
```
```{r}
#defining group
PC1_components <- pc$x #extracting the pc components
grouping <- PC1_components[,1] #extracting the PC1 component for separation

#Initializing the groups as I could not find another way to do it
group1 <- locations[2,]
group2 <- locations[1,]

n <- nrow(locations)
for (i in 1:n){
  if (grouping[i] > 0){
    group1 <- rbind(group1,locations[i,])
  }
  else {
    group2 <- rbind(group2,locations[i,])
  }
}
```

# Section 4:Illustrating the two groups on the interpolated model 
```{r}
#Gaussian distribution seems to subjectively fit the line, therefore, svm_gau is used for interpolation
xi <- seq(from=min(X),to=max(X),length.out=50)
yi <- seq(from=min(Y),to=max(Y),length.out=50)
zi <- kriging(x=X,y=Y,z=Z,svm=svm_gau,xi=xi,yi=yi,grid=TRUE)

colourplot(x=xi,y=yi,z=zi,key.title=title('Measured erosion rates (mm/yr)'), xlab='Eastings', ylab='Northings', extra={points(x=group1$E,y=group1$N ,pch=21,bg='white')}, main = "Group 1 on the Interpolated Plot")

colourplot(x=xi,y=yi,z=zi,key.title=title('Measured erosion rates (mm/yr)'), xlab='Eastings', ylab='Northings', extra={points(x=group2$E,y=group2$N ,pch=21,bg='grey')}, main ="Group 2 on the Interpolated Plot")
```